CREATE TABLE AS_SQUARES  (
  ID INTEGER PRIMARY KEY,
  SQUARE_ID TEXT NOT NULL,
  COLLECTED TEXT,
  LOCATION TEXT,
  AREA_NO TEXT,
  PEOPLE TEXT
);

CREATE TABLE AS_ARTIFACTS (
  ID INTEGER PRIMARY KEY,
  POTTERY TEXT,
  SQUARE INTEGER REFERENCES AS_SQUARES(ID)
);

CREATE TABLE AS_CONDITIONS (
  ID INTEGER PRIMARY KEY,
  WEATHER TEXT,
  SQUARE INTEGER REFERENCES AS_SQUARES(ID)
);

SELECT AddGeometryColumn('AS_SQUARES', 'GEOMETRY',
  2180, 'POLYGON', 'XY');

CREATE VIEW AS_FEATURES AS
SELECT S.ID AS FEATURE_ID, S.SQUARE_ID, S.COLLECTED, S.LOCATION, S.AREA_NO, S.PEOPLE, S.GEOMETRY,
       A.POTTERY,
       C.WEATHER
FROM AS_SQUARES S LEFT JOIN AS_ARTIFACTS A ON S.ID = A.SQUARE
                  LEFT JOIN AS_CONDITIONS C ON S.ID = C.SQUARE;

INSERT INTO VIEWS_GEOMETRY_COLUMNS VALUES ('as_features', 'geometry', 'feature_id', 'as_squares', 'geometry', 1);
