ALTER TABLE AS_SOURCES ADD
  COLUMN CHRONOLOGY_SEG_2 TEXT;

ALTER TABLE AS_SOURCES ADD
  COLUMN CULTURE_SEG_2 TEXT;

-- ver: 2

ALTER TABLE AS_SOURCES RENAME
  CHRONOLOGY CHRONOLOGY_SEG_1;

-- ver: 3



ALTER TABLE AS_SOURCES RENAME CULTURE CULTURE_SEG_1;

-- ver: 4
