ALTER TABLE AS_SOURCES ADD COLUMN culture2 TEXT;
ALTER TABLE AS_SOURCES ADD COLUMN chronology2 TEXT;
ALTER TABLE AS_SOURCES ADD COLUMN chronology_maybe TEXT;
ALTER TABLE AS_SOURCES ADD COLUMN culture_rel TEXT;
ALTER TABLE AS_SOURCES ADD COLUMN chronology_rel TEXT;
ALTER TABLE AS_SOURCES ADD COLUMN culture_maybe TEXT;

DROP VIEW AS_RECORDS;

CREATE VIEW AS_RECORDS AS
SELECT S.ID AS FEATURE_ID,
       S.SQUARE_ID AS 'SQUARE ID',
       S.SQUARE_DIMENSION AS 'SQUARE DIMENSION',
       S.AZP AS 'AZP NUMBER',
       S.SURVEY_DATE AS 'SURVEY DATE',
       S.PEOPLE AS 'PEOPLE',
       S.PLOW_DEPTH AS 'PLOW DEPTH',
       S.AGRO_TREATMENTS AS 'AGRICULTURAL TREATMENTS',
       S.WEATHER AS 'WEATHER',
       S.TEMPERATURE AS 'TEMPERATURE',
       S.OBSERVATION AS 'OBSERVATION',
       S.REMARKS AS 'OBSERVATION REMARKS',
       S.POTTERY,
       S.GLASS,
       S.BONES,
       S.METAL,
       S.FLINT,
       S.CLAY,
       S.OTHER,
       X.CHRONOLOGY,
       X.CULTURE,
       X.CHRONOLOGY2,
       X.CULTURE2,
       X.CHRONOLOGY_REL,
       X.CULTURE_REL,
       X.CHRONOLOGY_MAYBE,
       X.CULTURE_MAYBE,
       S.AUTHOR,
       S.S_REMARKS AS 'SOURCES REMARKS',
       S.GEOMETRY,
       S.SQUARE_ID,
       S.SQUARE_DIMENSION,
       S.AZP,
       S.SURVEY_DATE,
       S.PEOPLE,
       S.PLOW_DEPTH,
       S.AGRO_TREATMENTS,
       S.WEATHER,
       S.TEMPERATURE,
       S.OBSERVATION,
       S.REMARKS,
       S.S_REMARKS
FROM AS_SQUARES S LEFT JOIN AS_SOURCES X ON S.ID = X.SQUARE;

-- ver: 2
