ALTER TABLE AS_SOURCES ADD
  COLUMN CHRONOLOGY_SEG_2 TEXT;

ALTER TABLE AS_SOURCES ADD
  COLUMN CULTURE_SEG_2 TEXT;

-- ver: 2

ALTER TABLE AS_SOURCES ADD COLUMN
  CHRONOLOGY_SEG_1;

UPDATE AS_SOURCES SET CHRONOLOGY_SEG_1=CHRONOLOGY;
-- ver: 3



ALTER TABLE AS_SOURCES ADD COLUMN CULTURE_SEG_1 TEXT;


UPDATE AS_SOURCES SET CULTURE_SEG_1=CULTURE;
-- ver: 4
